### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by tskinn** [bvinc/gxi#5]
Add the ability to show line numbers. I would love to help out if I can. Can I assume that general strategy is to mimic the xi-mac implementation?

**Comment by bvinc** [comment]
Sorry, I'm way late at responding to this issue.  We have line numbers now!

The general strategy that I've been trying to follow is not to necessarily mimic xi-mac, but follow the xi principles of being a modern native gnome application, while being a complete implementation of the xi protocol and features.
