### ISSUE TITLE
[Runtime] Gtk-ERROR **: failed to add UI: resources/gxi.ui:19:1 <object> requires attribute "id"

### ISSUE THREAD

**Issue by fralix** [bvinc/gxi#6]
I was trying to rung gxi. cargo build went fine but execution fails like that:
```
fralix@lm17-3 ~/build/gxi $ target/debug/gxi

(.:542): Gtk-ERROR **: failed to add UI: resources/gxi.ui:19:1 <object> requires attribute "id"
Trace/breakpoint trap
fralix@lm17-3 ~/build/gxi $ 
```

**Comment by bvinc** [comment]
The reason I don't see this bug is because the required attribute `id` is only required by older versions of GTK.  What OS are you running?

I've changed a lot since this issue was created.  Every object tag now contains an `id` attribute.  This may be fixed already.

**Comment by fralix** [comment]
Exactly, updating the git repo + running it again works fine.
Nice work!
