### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by AdrianVovk** [bvinc/gxi#7]
Could you add a screenshot to the readme? I don't have time right now to try to compile it

**Comment by KyrychukD** [comment]
Here's a screenshot of how gxi looks today:
![gxi_001](https://user-images.githubusercontent.com/699961/40279801-c7db6fbe-5c51-11e8-90d9-3b7b2432dbaa.png)

**Comment by AdrianVovk** [comment]
Alright thank you
